import Head from 'next/head'
import Header from '../components/Header'
import Navigation from '../components/navigation'
import '../styles/globals.css'
import styles from '../styles/Home.module.css'

function MyApp({ Component, pageProps }) {

  return (
    <>
      <Head>
        <title>Katrina Cloyd Portfolio Site</title>
        <meta name="description" content="Developer and designer portfolio site generated by create next app" />
      </Head>
      <div className={styles.container}>
        <Header />
        <main className={styles.main}>
          <section className={styles.grid}>
            <Component {...pageProps} />
          </section>
          <Navigation />
        </main>
        <footer className={styles.footer}>
          <p>last update 7/2021</p>
        </footer>
      </div>
    </>
  )
}

export default MyApp
