import Head from 'next/head'
import Image from 'next/image'
import Navigation from '../components/navigation'
import Header from '../components/Header'
import styles from '../styles/Home.module.css'

export default function About() {
    return (
        <div className={styles.container}>
            <Head>
                <title>Katrina Cloyd Portfolio Site</title>
                <meta name="description" content="Developer and designer portfolio site generated by create next app" />
                {/* <link rel="icon" href="/favicon.ico" /> */}
            </Head>
            <Header />
            <main className={styles.main}>
                <p className={styles.grid}>I'm AM ABOUNT</p>
                <Navigation />
            </main>

            <footer className={styles.footer}>
                <p>Footer</p>
            </footer>
        </div>
    )
}