import Head from 'next/head'
import Image from 'next/image'
import Navigation from '../components/navigation'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Katrina Cloyd Portfolio Site</title>
        <meta name="description" content="Developer and designer portfolio site generated by create next app" />
        {/* <link rel="icon" href="/favicon.ico" /> */}
      </Head>

      <header>
        <h1>KATRINA CLOYD</h1>
      </header>
      <main className={styles.main}>
        <h3>
          Welcome to my portfolio site. I am glad you are here. This is still a work in progress. Slow pregress if I am being honest, becasue I am usting this as my first next.js project. Which is very exciting and fun, but also considerably slower, so thank you for your patience, and check back soon! Who knows maybe this will go more quickly than anticipated!
        </h3>
        <Navigation />
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Still learning with{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
