import Head from 'next/head'
import Navigation from '../components/navigation'
import Header from '../components/Header'
import { useState } from 'react'
import styles from '../styles/Home.module.css'

export default function Home() {
  const [page, setPage] = useState('home');

  return (
    <div className={styles.container}>
      <Head>
        <title>Katrina Cloyd Portfolio Site</title>
        <meta name="description" content="Developer and designer portfolio site generated by create next app" />
        {/* <link rel="icon" href="/favicon.ico" /> */}
      </Head>
      <Header />
      <main className={styles.main}>
        {page === 'home' &&
          <p className={styles.grid}>hello <br />
            and welcome to my portfolio site<br />
            i am a front end developer<br />
            designer<br />
            & artist<br />
            <br />
            here you can find info and examples of my work<br />
            <br />
            explore<br />
            & make your self at home<br />
            i’d love to hear what you think<br />
            <br />
            thanks for visiting!<br />
            <br />
            this is (obviously) still a work in progress... slow pregress if I am being honest, becasue I am usting this as my first next.js project<br />
            <br />
            which is very exciting and fun, but also considerably slower, so thank you for your patience, and check back soon! <br />
            <br />
            who knows maybe this will go more quickly than anticipated!
          </p>}
        {page === 'about' &&
          <p className={styles.grid}>about me
          </p>}
        {page === 'dev' &&
          <p className={styles.grid}>examples of my software engineering work coming soon
          </p>}
        {page === 'design' &&
          <p className={styles.grid}>examples of my design work coming soon
          </p>}
        {page === 'contact' &&
          <p className={styles.grid}>list of conatct icons
          </p>}
        <Navigation page={page} setPage={setPage} />
      </main>

      <footer className={styles.footer}>
        <p>last update 6/2021</p>
      </footer>
    </div>
  )
}
